name: Tests

on:
  push:
    branches: [main]

jobs:
  tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 24
      - name: Enable Corepack
        run: corepack enable
      - name: Install Dependencies
        run: NODE_OPTIONS='--openssl-legacy-provider' corepack yarn
      - name: Run Jest Unit Tests
        run: corepack yarn test
      - name: Build App
        run: NODE_OPTIONS='--openssl-legacy-provider' corepack yarn build
      - name: Install Playwright Browsers
        run: corepack yarn playwright install --with-deps
      - name: Run Playwright E2E Tests
        run: corepack yarn e2e
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 30
